// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input /data/common/code/qmk_firmware/keyboards/converter/adafruit_rp2040_usbh/monaspace.png --output /data/common/code/qmk_firmware/keyboards/converter/adafruit_rp2040_usbh --no-ascii False --unicode-glyphs  --format mono2 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_monaspace_length;
extern const uint8_t  font_monaspace[1870];
