# BOARD=GENERIC_RP_RP2040
BOOTLOADER=rp2040
EXTRAKEY_ENABLE=yes
TAP_DANCE_ENABLE=yes
OLED_ENABLE=no
QUANTUM_PAINTER_ENABLE=yes
QUANTUM_PAINTER_DRIVERS += sh1106_i2c
SRC += monaspace.qff.c
LEADER_ENABLE=yes
RGBLIGHT_ENABLE=no
WS2812_DRIVER=vendor
WEAR_LEVELING_DRIVER = rp2040_flash
EEPROM_DRIVER=spi
INTROSPECTION_KEYMAP_C = custom.c

COMMAND_ENABLE=yes
MAGIC_ENABLE=yes
COMBO_ENABLE=yes
SPACE_CADET_ENABLE=no

DYNAMIC_MACRO_ENABLE=yes
MOUSEKEY_ENABLE=yes

# too much space
AUDIO_ENABLE=yes
AUDIO_DRIVER=pwm_hardware

#linux doesn't recognize...
PROGRAMMABLE_BUTTON_ENABLE = no
# only for tiny kbds without dedicated esc
GRAVE_ESC_ENABLE=no

CONSOLE_ENABLE=yes
UNICODE_ENABLE=no
KEY_OVERRIDE_ENABLE=no
TERMINAL_ENABLE=no
